// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZMVbAyuOBRffhn1acFD38GR-eiHrmjo',
    appId: '1:661073920531:web:ecda23b95c0268f76075e6',
    messagingSenderId: '661073920531',
    projectId: 'vitali-1c9b0',
    authDomain: 'vitali-1c9b0.firebaseapp.com',
    storageBucket: 'vitali-1c9b0.appspot.com',
    measurementId: 'G-CH6CT6E48D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIe-Om8oHKZisPme4sX3liUwPOi3JBkOw',
    appId: '1:661073920531:android:5d4a6701f09ee4fc6075e6',
    messagingSenderId: '661073920531',
    projectId: 'vitali-1c9b0',
    storageBucket: 'vitali-1c9b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnz7OI-4fAm8ISvQRp6siPyFIhkFApWY',
    appId: '1:661073920531:ios:b00f0dd75a189f7f6075e6',
    messagingSenderId: '661073920531',
    projectId: 'vitali-1c9b0',
    storageBucket: 'vitali-1c9b0.appspot.com',
    iosBundleId: 'com.example.vitali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnz7OI-4fAm8ISvQRp6siPyFIhkFApWY',
    appId: '1:661073920531:ios:e891aafe9c19a5f96075e6',
    messagingSenderId: '661073920531',
    projectId: 'vitali-1c9b0',
    storageBucket: 'vitali-1c9b0.appspot.com',
    iosBundleId: 'com.example.vitali.RunnerTests',
  );
}
